// <auto-generated />
using System;
using BookLibraryApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookLibraryApp.Migrations
{
    [DbContext(typeof(BookLibraryContext))]
    partial class BookLibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BookLibraryApp.Models.Bookratings", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnName("User-ID")
                        .HasColumnType("int");

                    b.Property<string>("Isbn")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ISBN")
                        .HasColumnType("varchar(13)")
                        .HasDefaultValueSql("''")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_0900_ai_ci");

                    b.Property<int>("BookRating")
                        .HasColumnName("Book-Rating")
                        .HasColumnType("int");

                    b.HasKey("UserId", "Isbn")
                        .HasName("PRIMARY");

                    b.ToTable("bookratings");
                });

            modelBuilder.Entity("BookLibraryApp.Models.Books", b =>
                {
                    b.Property<string>("Isbn")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ISBN")
                        .HasColumnType("varchar(13)")
                        .HasDefaultValueSql("''")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_bin");

                    b.Property<string>("BookAuthor")
                        .HasColumnName("Book-Author")
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_0900_ai_ci");

                    b.Property<string>("BookTitle")
                        .HasColumnName("Book-Title")
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_0900_ai_ci");

                    b.Property<string>("ImageUrlL")
                        .HasColumnName("Image-URL-L")
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_bin");

                    b.Property<string>("ImageUrlM")
                        .HasColumnName("Image-URL-M")
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_bin");

                    b.Property<string>("ImageUrlS")
                        .HasColumnName("Image-URL-S")
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_bin");

                    b.Property<string>("Publisher")
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_0900_ai_ci");

                    b.Property<uint?>("YearOfPublication")
                        .HasColumnName("Year-Of-Publication")
                        .HasColumnType("int unsigned");

                    b.HasKey("Isbn")
                        .HasName("PRIMARY");

                    b.ToTable("books");
                });

            modelBuilder.Entity("BookLibraryApp.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("User-ID")
                        .HasColumnType("int");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("varchar(250)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_0900_ai_ci");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
